---

- name: Hello World
  hosts: 'all'
  gather_facts: false
  become: false

  tasks:
    - name: 'hello world'
      ansible.builtin.command: 'echo "Hello World!"'
      register: r_output

    - name: 'print output'
      ansible.builtin.debug:
        msg: '{{ r_output.stdout }}'
